### ISSUE TITLE
Plans for a similar repo for summer 2023? 

### ISSUE THREAD

**Issue by TheTallJerry** [jenndryden/Canadian-Tech-Internships-Summer-2023#38]
This repo helped me a ton for this current summer, and the next one is coming up. I’m already seeing postings up, not many yet but we can expect a huge drop soon. Wondering if there’re plans for another Canadian specific repo.

**Comment by AnimeAllstar** [comment]
Why not just Update this one to 2023?

**Comment by TheTallJerry** [comment]
That would work too, just gathering ideas

**Comment by ChrisDryden** [comment]
Thanks for the reminder, going to transfer this to @jenndryden and update the repo to 2023 and add the current postings

**Comment by ChrisDryden** [comment]
Which ones do you know of that opened already?

**Comment by TheTallJerry** [comment]
Hey sorry for the late reply, I can open a pr shortly.

**Comment by TheTallJerry** [comment]
Closing this issue as the repo has been revamped for summer 2023.
